<?xml version="1.0"?>

<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  	<xacro:include filename="$(find dynaarm_urdf)/urdf/dynaarm_inertial.urdf.xacro" />
        <xacro:property name="J_PI" value="3.1415926535897931" />

    <xacro:macro name="dynaarm_realsense" params="parent camera_name simulation_realsense realsense_pos_nbr realsense_type">

                <xacro:unless value="${realsense_pos_nbr-0}">
                  <xacro:if value="${realsense_type == 'l515'}">
                    <xacro:sensor_l515 parent="${parent}" name="${camera_name}">
                      <origin xyz="${joint_realsense_origin_festoHand_xyz}" rpy="${joint_realsense_origin_festoHand_rpy}"/>
                    </xacro:sensor_l515>
                  </xacro:if>
                  <xacro:if value="${realsense_type == 'd435'}">
                    <xacro:sensor_d435 parent="${parent}" name="${camera_name}">
                      <origin xyz="${joint_realsense_origin_festoHand_xyz}" rpy="${joint_realsense_origin_festoHand_rpy}"/>
                    </xacro:sensor_d435>
                  </xacro:if>
                </xacro:unless>
                <xacro:unless value="${realsense_pos_nbr-1}">
                  <xacro:if value="${realsense_type == 'l515'}">
                    <xacro:sensor_l515 parent="${parent}" name="${camera_name}">
                      <origin xyz="-0.035 -0.028 0.015" rpy="0 ${-J_PI/2} ${-J_PI/2}"/>
                    </xacro:sensor_l515>
                  </xacro:if>
                  <xacro:if value="${realsense_type == 'd435'}">
                    <xacro:sensor_d435 parent="${parent}" name="${camera_name}">
                      <origin xyz="0.0 -0.014 0.02015" rpy="${-J_PI/2} ${-J_PI/2} 0"/>
                    </xacro:sensor_d435>
                  </xacro:if>
                </xacro:unless>
                <xacro:unless value="${realsense_pos_nbr-2}">
                  <xacro:if value="${realsense_type == 'l515'}">
                    <xacro:sensor_l515 parent="${parent}" name="${camera_name}">
                      <origin xyz="-0.053 -0.0307 0.015" rpy="0 ${-J_PI/2} ${-J_PI/2}"/>
                    </xacro:sensor_l515>
                  </xacro:if>
                  <xacro:if value="${realsense_type == 'd435'}">
                    <xacro:sensor_d435 parent="${parent}" name="${camera_name}">
                      <origin xyz="-0.035 0.0 0.01" rpy="0 ${-J_PI/2} 0"/>
                    </xacro:sensor_d435>
                  </xacro:if>
                </xacro:unless>
                <xacro:unless value="${realsense_pos_nbr-3}">
                  <xacro:if value="${realsense_type == 'l515'}">
                    <xacro:sensor_l515 parent="${parent}" name="${camera_name}">
                      <origin xyz="-0.035 -0.028 0.015" rpy="0 ${-J_PI/2} ${-J_PI/2}"/>
                    </xacro:sensor_l515>
                  </xacro:if>
                  <xacro:if value="${realsense_type == 'd435'}">
                    <xacro:sensor_d435 parent="${parent}" name="${camera_name}">
                      <origin xyz="0.0 0.0441 ${0.0181+0.036}" rpy="0 -${J_PI/2} -${J_PI/2}"/>
                    </xacro:sensor_d435>
                  </xacro:if>
                </xacro:unless>
                <xacro:unless value="${realsense_pos_nbr-4}">
                  <xacro:if value="${realsense_type == 'l515'}">
                    <xacro:sensor_l515 parent="${parent}" name="${camera_name}">
                      <origin xyz="-0.03 0.0185 0.075" rpy="${J_PI/2} 0 ${J_PI/2}"/>
                    </xacro:sensor_l515>
                  </xacro:if>
                  <xacro:if value="${realsense_type == 'd435'}">
                    <xacro:sensor_d435 parent="${parent}" name="${camera_name}">
                      <origin xyz="0.0 0.014 0.0625" rpy="0 0 ${J_PI/2}"/>
                    </xacro:sensor_d435>
                  </xacro:if>
                </xacro:unless>
                <xacro:unless value="${realsense_pos_nbr-5}">
                  <xacro:if value="${realsense_type == 'l515'}">
                    <xacro:sensor_l515 parent="${parent}" name="${camera_name}">
                      <origin xyz="0.0 0.0 0.0" rpy="0 0 0"/>
                    </xacro:sensor_l515>
                  </xacro:if>
                  <xacro:if value="${realsense_type == 'd435'}">
                    <xacro:sensor_d435 parent="${parent}" name="${camera_name}">
                      <origin xyz="0.065 0.0 -0.066" rpy="0 0 0"/>
                    </xacro:sensor_d435>
                  </xacro:if>
                </xacro:unless>                
                <!-- camera on drive -->
                <xacro:unless value="${realsense_pos_nbr-6}">
                  <xacro:if value="${realsense_type == 'l515'}">
                    <xacro:sensor_l515 parent="${parent}" name="${camera_name}">
                      <origin xyz="-0.019 0.032 0.0" rpy="${J_PI/2} 0 ${J_PI}"/>
                    </xacro:sensor_l515>
                  </xacro:if>
                  <xacro:if value="${realsense_type == 'd435'}">
                    <xacro:sensor_d435 parent="${parent}" name="${camera_name}">
                      <origin xyz="0.02 0.15 0.0" rpy="${J_PI/2} 0 -0.4"/>
                    </xacro:sensor_d435>
                  </xacro:if>
                </xacro:unless>
          <xacro:if value="${simulation_realsense}">
            <!-- Gazebo plugin -->
            <gazebo reference="${camera_name}_link">
              <sensor type="depth" name="${camera_name}">
                <always_on>1</always_on>
                <visualize>true</visualize>
                <camera>
                  <horizontal_fov>1.5917</horizontal_fov> <!-- 91.2 degrees -->
                  <image>
                    <width>424</width>
                    <height>240</height>
                    <format>R8G8B8</format>
                  </image>
                  <depth_camera>

                  </depth_camera>
                  <clip>
                    <near>0.02</near>
                    <far>10.0</far>
                  </clip>
                </camera>
                <plugin name="camera_controller" filename="libgazebo_ros_openni_kinect.so">
                  <alwaysOn>true</alwaysOn>
                  <updateRate>0.0</updateRate>
                  <cameraName>${camera_name}</cameraName>
                  <frameName>${camera_name}_depth_optical_frame</frameName>
                  <imageTopicName>color/image_raw</imageTopicName>
                  <depthImageTopicName>aligned_depth_to_color/image_raw</depthImageTopicName>
                  <pointCloudTopicName>depth/color/points</pointCloudTopicName>
                  <cameraInfoTopicName>color/camera_info</cameraInfoTopicName>
                  <depthImageCameraInfoTopicName>aligned_depth_to_color/camera_info</depthImageCameraInfoTopicName>
                  <pointCloudCutoff>0.1</pointCloudCutoff>
                  <pointCloudCutoffMax>3.0</pointCloudCutoffMax>
                  <hackBaseline>0.05</hackBaseline>
                  <distortionK1>0.0</distortionK1>
                  <distortionK2>0.0</distortionK2>
                  <distortionK3>0.0</distortionK3>
                  <distortionT1>0.0</distortionT1>
                  <distortionT2>0.0</distortionT2>
                  <CxPrime>0.0</CxPrime>
                  <Cx>0.0</Cx>
                  <Cy>0.0</Cy>
                  <focalLength>0.0</focalLength>
                </plugin>
              </sensor>
            </gazebo>
          </xacro:if>


    </xacro:macro>

    <xacro:macro name="sensor_d435" params="parent *origin name:=camera">
                <xacro:property name="M_PI" value="3.1415926535897931" />

                <!-- The following values are approximate, and the camera node
                 publishing TF values with actual calibrated camera extrinsic values -->
                <xacro:property name="d435_cam_depth_to_left_ir_offset" value="0.0"/>
                <xacro:property name="d435_cam_depth_to_right_ir_offset" value="-0.050"/>
                <xacro:property name="d435_cam_depth_to_color_offset" value="0.015"/>

                <!-- The following values model the aluminum peripherial case for the
                    D435 camera, with the camera joint represented by the actual
                    peripherial camera tripod mount -->
                <xacro:property name="d435_cam_width" value="0.090"/>
                <xacro:property name="d435_cam_height" value="0.025"/>
                <xacro:property name="d435_cam_depth" value="0.02505"/>
                <xacro:property name="d435_cam_mount_from_center_offset" value="0.0149"/>

                <!-- The following offset is relative the the physical D435 camera peripherial
                    camera tripod mount -->
                <xacro:property name="d435_cam_depth_px" value="${d435_cam_mount_from_center_offset}"/>
                <xacro:property name="d435_cam_depth_py" value="0.0175"/>
                <xacro:property name="d435_cam_depth_pz" value="${d435_cam_height/2}"/>

                <material name="aluminum">
                      <color rgba="0.5 0.5 0.5 1"/>
                </material>


                <!-- camera body, with origin at bottom screw mount -->
                <joint name="camera_joint" type="fixed">
                  <xacro:insert_block name="origin" />
                  <parent link="${parent}"/>
                  <child link="${name}_bottom_screw_frame" />
                </joint>
                <link name="${name}_bottom_screw_frame"/>

                <joint name="${name}_link_joint" type="fixed">
                  <origin xyz="0 ${d435_cam_depth_py} ${d435_cam_depth_pz}" rpy="0 0 0"/>
                  <parent link="${name}_bottom_screw_frame"/>
                  <child link="${name}_link" />
                </joint>

                <link name="${name}_link">
                  <visual>
                  <origin xyz="${d435_cam_mount_from_center_offset} ${-d435_cam_depth_py} 0" rpy="${M_PI/2} 0 ${M_PI/2}"/>
                    <geometry>
                      <!-- <box size="${d435_cam_width} ${d435_cam_height} ${d435_cam_depth}"/> -->
                            <mesh filename="package://dynaarm_urdf/meshes/d435.dae" />
                      <!--<mesh filename="package://realsense2_camera/meshes/d435/d435.dae" />-->

                    </geometry>
                    <material name="aluminum"/>
                  </visual>
                  <collision>
                    <origin xyz="0 ${-d435_cam_depth_py} 0" rpy="0 0 0"/>
                    <geometry>
                    <box size="${d435_cam_depth} ${d435_cam_width} ${d435_cam_height}"/>
                    </geometry>
                  </collision>
                  <inertial>
                    <mass value="0.072" />
                    <origin xyz="0 0 0" />
                    <inertia ixx="0.00005235" ixy="0.0" ixz="0.0" iyy="0.0000075" iyz="0.0" izz="0.00005235" />
                  </inertial>
                </link>

                <!-- camera depth joints and links -->
                <joint name="${name}_depth_joint" type="fixed">
                  <origin xyz="0 0 0" rpy="0 0 0"/>
                  <parent link="${name}_link"/>
                  <child link="${name}_depth_frame" />
                </joint>
                <link name="${name}_depth_frame"/>

                <joint name="${name}_depth_optical_joint" type="fixed">
                  <origin xyz="0 0 0" rpy="${-M_PI/2} 0 ${-M_PI/2}" />
                  <parent link="${name}_depth_frame" />
                  <child link="${name}_depth_optical_frame" />
                </joint>
                <link name="${name}_depth_optical_frame"/>

                <!-- camera left IR joints and links -->
                <joint name="${name}_left_ir_joint" type="fixed">
                  <origin xyz="0 ${d435_cam_depth_to_left_ir_offset} 0" rpy="0 0 0" />
                  <parent link="${name}_depth_frame" />
                  <child link="${name}_left_ir_frame" />
                </joint>
                <link name="${name}_left_ir_frame"/>

                <joint name="${name}_left_ir_optical_joint" type="fixed">
                  <origin xyz="0 0 0" rpy="${-M_PI/2} 0 ${-M_PI/2}" />
                  <parent link="${name}_left_ir_frame" />
                  <child link="${name}_left_ir_optical_frame" />
                </joint>
                <link name="${name}_left_ir_optical_frame"/>

                <!-- camera right IR joints and links -->
                <joint name="${name}_right_ir_joint" type="fixed">
                  <origin xyz="0 ${d435_cam_depth_to_right_ir_offset} 0" rpy="0 0 0" />
                  <parent link="${name}_depth_frame" />
                  <child link="${name}_right_ir_frame" />
                </joint>
                <link name="${name}_right_ir_frame"/>

                <joint name="${name}_right_ir_optical_joint" type="fixed">
                  <origin xyz="0 0 0" rpy="${-M_PI/2} 0 ${-M_PI/2}" />
                  <parent link="${name}_right_ir_frame" />
                  <child link="${name}_right_ir_optical_frame" />
                </joint>
                <link name="${name}_right_ir_optical_frame"/>

                <!-- camera color joints and links -->
                <joint name="${name}_color_joint" type="fixed">
                  <origin xyz="0 ${d435_cam_depth_to_color_offset} 0" rpy="0 0 0" />
                  <parent link="${name}_depth_frame" />
                  <child link="${name}_color_frame" />
                </joint>
                <link name="${name}_color_frame"/>

                <joint name="${name}_color_optical_joint" type="fixed">
                  <origin xyz="0 0 0" rpy="${-M_PI/2} 0 ${-M_PI/2}" />
                  <parent link="${name}_color_frame" />
                  <child link="${name}_color_optical_frame" />
                </joint>
                <link name="${name}_color_optical_frame"/>
    </xacro:macro>

    <xacro:macro name="sensor_l515" params="parent *origin name:=camera use_nominal_extrinsics:=true add_plug:=false use_mesh:=true">
      <xacro:property name="M_PI" value="3.1415926535897931" />

      <!-- The following values are approximate, and the camera node
       publishing TF values with actual calibrated camera extrinsic values -->
      <xacro:property name="l515_cam_depth_to_infra_offset" value="0.0"/>

      <!-- The following values model the aluminum peripherial case for the
       L515 camera, with the camera joint represented by the actual
       peripherial camera tripod mount -->
      <xacro:property name="l515_cam_width" value="0.061"/>
      <xacro:property name="l515_cam_height" value="0.06065"/>
      <xacro:property name="l515_cam_depth" value="0.026"/>
      <xacro:property name="l515_cam_mount_from_glass_offset" value="0.012"/>
      <!-- Zero depth to glass: see datasheet Revision 002, Fig. 2-2 page 11 -->
      <xacro:property name="l515_zero_depth_to_glass" value="0.0045"/> 
      <!-- convenience precomputation to avoid clutter-->
      <xacro:property name="l515_depth_x_offset_from_mount" value="${l515_cam_mount_from_glass_offset-l515_zero_depth_to_glass}"/>

      <!-- The following offset is relative the the physical D435 camera peripherial
       camera tripod mount -->
      <xacro:property name="l515_cam_depth_px" value="${l515_depth_x_offset_from_mount}"/>
      <xacro:property name="l515_cam_depth_py" value="0.0"/>
      <xacro:property name="l515_cam_center"   value="0.03015"/>
      <xacro:property name="l515_cam_center_to_transmitter_pz"  value="0.001"/>
      <xacro:property name="l515_cam_transmitter_to_depth_pz"   value="-0.010"/>
      <xacro:property name="l515_cam_transmitter_to_color_pz"   value="0.014"/>
      <xacro:property name="l515_cam_depth_pz" value="${l515_cam_center+l515_cam_center_to_transmitter_pz+l515_cam_transmitter_to_depth_pz}"/>
      <xacro:property name="l515_cam_center_to_depth_pz" value="${l515_cam_center_to_transmitter_pz+l515_cam_transmitter_to_depth_pz}"/>
      <xacro:property name="abs_mount_from_center"   value="0.020"/>

      <!-- camera body, with origin at bottom screw mount -->
      <joint name="${name}_joint" type="fixed">
        <xacro:insert_block name="origin" />
        <parent link="${parent}"/>
        <child link="${name}_bottom_screw_frame" />
      </joint>
      <link name="${name}_bottom_screw_frame"/>

      <joint name="${name}_link_joint" type="fixed">
        <origin xyz="${l515_cam_depth_px} ${l515_cam_depth_py} ${l515_cam_depth_pz}" rpy="0 0 0"/>
        <parent link="${name}_bottom_screw_frame"/>
        <child link="${name}_link" />
      </joint>

      <link name="${name}_link">
        <visual>
          <!-- the mesh origin is in the middle of the front plate -->
          <xacro:if value="${use_mesh}">
            <origin xyz="${l515_zero_depth_to_glass} 0 ${-l515_cam_center_to_depth_pz}" rpy="${M_PI/2} 0 ${M_PI/2}"/>
            <geometry>
                <mesh filename="package://dynaarm_urdf/meshes/l515.dae" />
            </geometry>
          </xacro:if>
          <xacro:unless value="${use_mesh}">
            <origin xyz="${-l515_cam_depth_px+l515_cam_mount_from_glass_offset-l515_cam_depth/2} 0 ${-l515_cam_center_to_depth_pz}" rpy="${M_PI/2} 0 ${M_PI/2}"/>
            <geometry>
              <cylinder radius="${l515_cam_width/2.0}" length="${l515_cam_depth}"/>
            </geometry>
            <material name="aluminum"/>
          </xacro:unless>
        </visual>
        <collision>
          <origin xyz="${-l515_cam_depth_px+l515_cam_mount_from_glass_offset-l515_cam_depth/2} 0 ${-l515_cam_center_to_depth_pz}" rpy="${M_PI/2} 0 ${M_PI/2}"/>
          <geometry>
            <cylinder radius="${l515_cam_width/2.0}" length="${l515_cam_depth}"/>
          </geometry>
        </collision>
        <inertial>
          <!-- The following are not reliable values, and should not be used for modeling -->
          <!-- calculated assuming full cylinder as described here: https://en.wikipedia.org/wiki/List_of_moments_of_inertia -->
          <mass value="0.095" />
          <origin xyz="0 0 0" />
          <inertia ixx="0.000044" ixy="0.0" ixz="0.0" iyy="0.000027" iyz="0.0" izz="0.000027" />
        </inertial>
      </link>

      <joint name="${name}_lower_mount_joint" type="fixed">
        <origin xyz="${l515_cam_mount_from_glass_offset-l515_cam_depth} 0 ${l515_cam_center-abs_mount_from_center}" rpy="0 0 0" />
        <parent link="${name}_bottom_screw_frame" />
        <child link="${name}_lower_mount" />
      </joint>
      <link name="${name}_lower_mount"/>

      <joint name="${name}_upper_mount_joint" type="fixed">
        <origin xyz="${l515_cam_mount_from_glass_offset-l515_cam_depth} 0 ${l515_cam_center+abs_mount_from_center}" rpy="0 0 0" />
        <parent link="${name}_bottom_screw_frame" />
        <child link="${name}_upper_mount" />
      </joint>
      <link name="${name}_upper_mount"/>

      <!-- Use the nominal extrinsics between camera frames if the calibrated extrinsics aren't being published. e.g. running the device in simulation  -->
      <xacro:if value="${use_nominal_extrinsics}">
        <!-- camera depth joints and links -->
        <joint name="${name}_depth_joint" type="fixed">
          <origin xyz="0 0 0" rpy="0 0 0"/>
          <parent link="${name}_link"/>
          <child link="${name}_depth_frame" />
        </joint>
        <link name="${name}_depth_frame"/>

        <joint name="${name}_depth_optical_joint" type="fixed">
          <origin xyz="0 0 0" rpy="${-M_PI/2} 0 ${-M_PI/2}" />
          <parent link="${name}_depth_frame" />
          <child link="${name}_depth_optical_frame" />
        </joint>
        <link name="${name}_depth_optical_frame"/>

        <!-- camera left IR joints and links -->
        <joint name="${name}_infra_joint" type="fixed">
          <origin xyz="0 ${l515_cam_depth_to_infra_offset} 0" rpy="0 0 0" />
          <parent link="${name}_link" />
          <child link="${name}_infra_frame" />
        </joint>
        <link name="${name}_infra_frame"/>

        <joint name="${name}_infra_optical_joint" type="fixed">
          <origin xyz="0 0 0" rpy="${-M_PI/2} 0 ${-M_PI/2}" />
          <parent link="${name}_infra_frame" />
          <child link="${name}_infra_optical_frame" />
        </joint>
        <link name="${name}_infra_optical_frame"/>

        <!-- camera color joints and links -->
        <joint name="${name}_color_joint" type="fixed">
          <origin xyz="0 0 ${-l515_cam_transmitter_to_depth_pz+l515_cam_transmitter_to_color_pz}" rpy="0 0 0" />
          <parent link="${name}_link" />
          <child link="${name}_color_frame" />
        </joint>
        <link name="${name}_color_frame"/>

        <joint name="${name}_color_optical_joint" type="fixed">
          <origin xyz="0 0 0" rpy="${-M_PI/2} 0 ${-M_PI/2}" />
          <parent link="${name}_color_frame" />
          <child link="${name}_color_optical_frame" />
        </joint>
        <link name="${name}_color_optical_frame"/>
      </xacro:if>
      <xacro:if value="${add_plug}">
        <xacro:usb_plug parent="${name}_bottom_screw_frame" name="${name}_usb_plug">
          <origin xyz="${l515_cam_mount_from_glass_offset-0.0148} -0.018 0.018" rpy="${M_PI/4} 0 0 "/>
        </xacro:usb_plug>
      </xacro:if>
    </xacro:macro>    

</robot>
