<?xml version="1.0"?>

<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

<xacro:macro name="dynaarm_endeffector" params="parent_link gripper_base_origin_xyz gripper_base_origin_rpy gripper_yaw ft_sensor_orientation_z">

        <xacro:dynaarm_link link_name="ftSensor_interfacePlate" file_name="${link04_4tube_ftsPlate_mesh}" link_nbr="${link04_4tube_ftsPlate_nbr}" />
        <xacro:dynaarm_joint_fixed joint_name="ftSensor_interfacePlate" parent="${parent_link}" child="ftSensor_interfacePlate" joint_origin_xyz="${gripper_base_origin_xyz}" joint_origin_rpy="0 0 0" />
        <xacro:dynaarm_link link_name="ftSensor_interfacePlate2" file_name="${link04_4tube_ftsPlate_mesh}" link_nbr="${link04_4tube_ftsPlate_nbr}" />
        <xacro:dynaarm_joint_fixed joint_name="ftSensor_interfacePlate2" parent="ftSensor_interfacePlate" child="ftSensor_interfacePlate2" joint_origin_xyz="0 0 0.006" joint_origin_rpy="0 0 0" />

        <xacro:virtual_link link_name="realsense_base" />

        <xacro:if value="${use_ftSensor_property}">
                <xacro:dynaarm_link link_name="ftSensor_link" file_name="${link04_4tube_ftSensor_mesh}" link_nbr="${link04_4tube_ftSensor_nbr}" />
                <xacro:dynaarm_joint_fixed joint_name="ftSensor_link_joint" parent="ftSensor_interfacePlate2" child="ftSensor_link" joint_origin_xyz="0.0 0.0 0.006" joint_origin_rpy="0 0 ${ft_sensor_orientation_z}" />
                <xacro:virtual_link link_name="ftSensor"/>
                <!-- 0.035 for old and 0.038 for new sensor -->
                <xacro:dynaarm_joint_fixed joint_name="ftSensor_joint" parent="ftSensor_link" child="ftSensor" joint_origin_xyz="0.0 0.0 ${ft_sensor_size}" joint_origin_rpy="0 0 0" />
                <!-- Dummy link used to allow for changing the orientation of the mounted ft sensor without changing ee orientation -->
                <xacro:virtual_link link_name="dummy_post_ftSensr_link" />
                <xacro:dynaarm_joint_fixed joint_name="post_ftSensor_dummy" parent="ftSensor_link" child="dummy_post_ftSensr_link" joint_origin_xyz="0.0 0.0 0.0" joint_origin_rpy="0 0 ${-ft_sensor_orientation_z}" />

                <xacro:dynaarm_joint_fixed joint_name="ftSensor_gripperBase" parent="dummy_post_ftSensr_link" child="realsense_base" joint_origin_xyz="0.0 0.0 ${ft_sensor_size-0.003}" joint_origin_rpy="${gripper_base_origin_rpy}" />
                <gazebo reference="ftSensor_joint">
                        <provideFeedback>true</provideFeedback>
                        <preserveFixedJoint>true</preserveFixedJoint>
                </gazebo>

                <!-- <gazebo> 
                <plugin name="ft_sensor" filename="libgazebo_ros_ft_sensor.so">
                        <updateRate>25.0</updateRate>
                        <always_on>true</always_on> 
                        <topicName>/fts_readings</topicName>
                        <jointName>ftSensor_joint</jointName>
                </plugin>
                </gazebo>                            -->
                <gazebo>
                        <plugin name="ft_sensor" filename="librokubimini_rsl_gazebo_plugin.so">
                                <statePublisherRate>25.0</statePublisherRate>
                                <robotNamespace>dynaarm</robotNamespace>
                                <topicName>/rokubimini_cosmo/ft_sensor/readings</topicName>
                                <bodyName>ftSensor_joint</bodyName>
                        </plugin>
                </gazebo>
                <xacro:if value="${use_realsense_fts_property}">
                   <xacro:dynaarm_link link_name="ftSensor_realsense_adapter" file_name="${fts_realsense_adapter_mesh}" link_nbr="${fts_realsense_adapter_nbr}" scale_value="0.001"/>                   
                   <!-- there is 0.038 offset because the mesh of the realsense mount was exported wrt the actual frame of the new force torque sensor -->
                   <xacro:dynaarm_joint_fixed joint_name="ftSensor_realsense_adapter_joint"
                         parent="ftSensor_link" child="ftSensor_realsense_adapter"
                         joint_origin_xyz=" 0.0 0.0 0.038" joint_origin_rpy="0 0 ${J_PI}" />
                        
                   <xacro:dynaarm_link link_name="ftSensor_realsense_mount" file_name="${link04_elbow_realsense_mount_mesh}" link_nbr="${link04_elbow_realsense_nbr}" scale_value="0.001"/>
                   
                   <!-- 0 deg -->
                   <xacro:unless value="${realsense_mount_angle_property}">
                       <xacro:dynaarm_joint_fixed joint_name="ftSensor_realsense_mount_joint"
                         parent="ftSensor_realsense_adapter" child="ftSensor_realsense_mount"
                         joint_origin_xyz="0.0579 0.0 -0.02" joint_origin_rpy="${J_PI/2.0} ${J_PI/2.0} 0" />
                   </xacro:unless>
           
                   <!-- 15 deg -->
                   <xacro:unless value="${realsense_mount_angle_property - 1}">
                       <xacro:dynaarm_joint_fixed joint_name="ftSensor_realsense_mount_joint"
                                parent="ftSensor_realsense_adapter" child="ftSensor_realsense_mount"
                                joint_origin_xyz="0.0579 0.0 -0.02" joint_origin_rpy="${J_PI/2.0} ${J_PI/2.0+0.261799} 0" />
                   </xacro:unless>
           
                   <!-- 17.5 deg -->
                   <xacro:unless value="${realsense_mount_angle_property - 2}">
                           <xacro:dynaarm_joint_fixed joint_name="ftSensor_realsense_mount_joint"
                                parent="ftSensor_realsense_adapter" child="ftSensor_realsense_mount"
                                joint_origin_xyz="0.0579 0.0 -0.02" joint_origin_rpy="${J_PI/2.0} ${J_PI/2.0+0.3054326} 0" />
                   </xacro:unless>
           
                   <!-- 20 deg -->
                   <xacro:unless value="${realsense_mount_angle_property - 3}">
                           <xacro:dynaarm_joint_fixed joint_name="ftSensor_realsense_mount_joint"
                                parent="ftSensor_realsense_adapter" child="ftSensor_realsense_mount"
                                joint_origin_xyz="0.0579 0.0 -0.02" joint_origin_rpy="${J_PI/2.0} ${J_PI/2.0+0.349066} 0" /> 
                   </xacro:unless>
                   <xacro:dynaarm_realsense parent="ftSensor_realsense_mount" camera_name="${realsense}" simulation_realsense="${simulation_property}" realsense_pos_nbr="6" realsense_type="${realsense_type_property}"/>
                </xacro:if>        
        </xacro:if>
        <xacro:unless value="${use_ftSensor_property}">
                <xacro:dynaarm_joint_fixed joint_name="gripper_base_joint" parent="ftSensor_interfacePlate2" child="realsense_base" joint_origin_xyz="0 0 0.006" joint_origin_rpy="${gripper_base_origin_rpy}" />
        </xacro:unless>

        <xacro:virtual_link link_name="gripper_base" />

        <xacro:if value="${use_realsense_wrist_property}">
                <xacro:dynaarm_link link_name="${link06}_realsense_adapter" file_name="${link06_realsense_adapter_mesh}" link_nbr="${link06_realsense_adapter_nbr}" />
                <xacro:dynaarm_joint_fixed joint_name="${joint_6_name}_realsense_adapter" parent="realsense_base" child="${link06}_realsense_adapter" joint_origin_xyz="0.0 0.0 0.0" joint_origin_rpy="${J_PI/2} 0 ${J_PI/2}" />
                <xacro:dynaarm_realsense parent="${link06}_realsense_adapter" camera_name="${realsense}" simulation_realsense="${simulation_property}" realsense_pos_nbr="4" realsense_type="${realsense_type_property}"/>
                <xacro:dynaarm_joint_fixed joint_name="${joint_6_name}gripper_base_realsense" parent="${link06}_realsense_adapter" child="gripper_base" joint_origin_xyz="0.0 0.004 0.0" joint_origin_rpy="${-J_PI/2} ${-J_PI/2} 0" />
        </xacro:if>
        <xacro:unless value="${use_realsense_wrist_property}">
                <xacro:dynaarm_joint_fixed joint_name="${joint_6_name}_realsense_base" parent="realsense_base" child="gripper_base" joint_origin_xyz="0.0 0.0 0.0" joint_origin_rpy="0 0 0" />
        </xacro:unless>

        <xacro:if value="${gripper_property == 'Robotiq'}">
                <xacro:robotiq_gripper parent="gripper_base" prefix="gripper" origin_rqy="0 0 ${gripper_yaw}"/>
                <xacro:dynaarm_endeffector_frame endeffector_origin_xyz="${joint_ee_origin_robotiq_xyz}" endeffector_origin_rpy="0 0 0" parent="gripper_base"/>
        </xacro:if>

        <xacro:if value="${gripper_property == 'EZgripper'}">
                <xacro:ez_gripper parent="gripper_base" prefix="gripper" origin_rqy="0 -1.57 0" fixed_fingers="false"/>
                <xacro:dynaarm_endeffector_frame endeffector_origin_xyz="${joint_ee_origin_ezgripper_xyz}" endeffector_origin_rpy="0 0 0" parent="gripper_base"/>
        </xacro:if>

        <xacro:if value="${gripper_property == 'AbilityHand'}">
                <xacro:ability_hand parent="gripper_base" origin_rqy="0 3.141592653589793 1.5707963267948966" origin_xyz="0 -0.03 0.04"/>
                <xacro:dynaarm_endeffector_frame endeffector_origin_xyz="${joint_ee_origin_ability_hand_xyz}" endeffector_origin_rpy="0 0 0" parent="gripper_base"/>
        </xacro:if>

        <xacro:if value="${gripper_property == 'CatchingNet'}">
                <xacro:dynaarm_link link_name="catchingNet" file_name="${link04_4tube_catchingNet_mesh}" link_nbr="${link04_4tube_catchingNet_nbr}" />
                <xacro:dynaarm_joint_fixed joint_name="gripper_base" parent="gripper_base" child="catchingNet" joint_origin_xyz="0 0 0" joint_origin_rpy="0 0 0" />
                <xacro:dynaarm_endeffector_frame endeffector_origin_xyz="${joint_ee_origin_4tube_catchingNet_xyz}" endeffector_origin_rpy="${joint_ee_origin_rpy}" parent="gripper_base"/>
        </xacro:if>

        <xacro:if value="${gripper_property == 'Mocap'}">
                <xacro:dynaarm_link link_name="ee_mocap_mount" file_name="${end_effector_mocap_mount_mesh}" link_nbr="${end_effector_mocap_mount_nbr}" scale_value="${mm_to_m}" />
                <xacro:dynaarm_joint_fixed joint_name="gripper_base" parent="gripper_base" child="ee_mocap_mount" joint_origin_xyz="0.0 0.0 -0.012" joint_origin_rpy="0 0 0" />
                <xacro:dynaarm_endeffector_frame endeffector_origin_xyz="${joint_ee_origin_mocap_mount_xyz}" endeffector_origin_rpy="0 0 0" parent="ee_mocap_mount"/>
        </xacro:if>

        <xacro:if value="${gripper_property == ''}">
                <xacro:dynaarm_endeffector_frame endeffector_origin_xyz="0 0 0" endeffector_origin_rpy="0 0 0" parent="gripper_base"/>
        </xacro:if>

</xacro:macro>

</robot>
