//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;
using RosMessageTypes.Std;

namespace RosMessageTypes.Crs
{
    [Serializable]
    public class Bool_array_stampedMsg : Message
    {
        public const string k_RosMessageName = "crs_msgs/bool_array_stamped";
        public override string RosMessageName => k_RosMessageName;

        public HeaderMsg header;
        public bool[] data;

        public Bool_array_stampedMsg()
        {
            this.header = new HeaderMsg();
            this.data = new bool[0];
        }

        public Bool_array_stampedMsg(HeaderMsg header, bool[] data)
        {
            this.header = header;
            this.data = data;
        }

        public static Bool_array_stampedMsg Deserialize(MessageDeserializer deserializer) => new Bool_array_stampedMsg(deserializer);

        private Bool_array_stampedMsg(MessageDeserializer deserializer)
        {
            this.header = HeaderMsg.Deserialize(deserializer);
            deserializer.Read(out this.data, sizeof(bool), deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.WriteLength(this.data);
            serializer.Write(this.data);
        }

        public override string ToString()
        {
            return "Bool_array_stampedMsg: " +
            "\nheader: " + header.ToString() +
            "\ndata: " + System.String.Join(", ", data.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
