//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;
using RosMessageTypes.Std;

namespace RosMessageTypes.Crs
{
    [Serializable]
    public class Car_steer_stateMsg : Message
    {
        public const string k_RosMessageName = "crs_msgs/car_steer_state";
        public override string RosMessageName => k_RosMessageName;

        //  This is a message to hold the steering data from a car.
        // 
        //  The steering data consist of the readout of the ADC on the car, which reads
        //  the position feedback signal from the potentiometer of the steering actuator.
        // 
        public HeaderMsg header;
        public float steer_angle;
        //  Position of the wheels in radians
        public short steer_discrete_pos;
        //  [mV] reading of the potentiometer

        public Car_steer_stateMsg()
        {
            this.header = new HeaderMsg();
            this.steer_angle = 0.0f;
            this.steer_discrete_pos = 0;
        }

        public Car_steer_stateMsg(HeaderMsg header, float steer_angle, short steer_discrete_pos)
        {
            this.header = header;
            this.steer_angle = steer_angle;
            this.steer_discrete_pos = steer_discrete_pos;
        }

        public static Car_steer_stateMsg Deserialize(MessageDeserializer deserializer) => new Car_steer_stateMsg(deserializer);

        private Car_steer_stateMsg(MessageDeserializer deserializer)
        {
            this.header = HeaderMsg.Deserialize(deserializer);
            deserializer.Read(out this.steer_angle);
            deserializer.Read(out this.steer_discrete_pos);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.Write(this.steer_angle);
            serializer.Write(this.steer_discrete_pos);
        }

        public override string ToString()
        {
            return "Car_steer_stateMsg: " +
            "\nheader: " + header.ToString() +
            "\nsteer_angle: " + steer_angle.ToString() +
            "\nsteer_discrete_pos: " + steer_discrete_pos.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
