//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;
using RosMessageTypes.Std;

namespace RosMessageTypes.Crs
{
    [Serializable]
    public class Car_inputMsg : Message
    {
        public const string k_RosMessageName = "crs_msgs/car_input";
        public override string RosMessageName => k_RosMessageName;

        //  Input given to a car robot.
        public HeaderMsg header;
        //  ---- Throttle actuators ----
        //  References for the throttle actuator. Note that only one of the fields
        //  "torque" and "velocity" should be set. The other should be set to NaN.
        //  If both are set, the torque reference will be used.
        public double torque;
        public double velocity;
        //  Reference for the steer actuator. This is an angle in radians.
        public double steer;
        //  In some cases the car's low-level steer map should be overriden (e.g., for
        //  system identification). If this flag is set to true, then the steer field
        //  is not interpreted as an angle in radians, but as a voltage reference for the
        //  potentiometer in the cars.
        public bool steer_override;

        public Car_inputMsg()
        {
            this.header = new HeaderMsg();
            this.torque = 0.0;
            this.velocity = 0.0;
            this.steer = 0.0;
            this.steer_override = false;
        }

        public Car_inputMsg(HeaderMsg header, double torque, double velocity, double steer, bool steer_override)
        {
            this.header = header;
            this.torque = torque;
            this.velocity = velocity;
            this.steer = steer;
            this.steer_override = steer_override;
        }

        public static Car_inputMsg Deserialize(MessageDeserializer deserializer) => new Car_inputMsg(deserializer);

        private Car_inputMsg(MessageDeserializer deserializer)
        {
            this.header = HeaderMsg.Deserialize(deserializer);
            deserializer.Read(out this.torque);
            deserializer.Read(out this.velocity);
            deserializer.Read(out this.steer);
            deserializer.Read(out this.steer_override);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.Write(this.torque);
            serializer.Write(this.velocity);
            serializer.Write(this.steer);
            serializer.Write(this.steer_override);
        }

        public override string ToString()
        {
            return "Car_inputMsg: " +
            "\nheader: " + header.ToString() +
            "\ntorque: " + torque.ToString() +
            "\nvelocity: " + velocity.ToString() +
            "\nsteer: " + steer.ToString() +
            "\nsteer_override: " + steer_override.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
