//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;
using RosMessageTypes.Std;

namespace RosMessageTypes.Crs
{
    [Serializable]
    public class Car_comMsg : Message
    {
        public const string k_RosMessageName = "crs_msgs/car_com";
        public override string RosMessageName => k_RosMessageName;

        public HeaderMsg header;
        public byte steer;
        public byte torque;

        public Car_comMsg()
        {
            this.header = new HeaderMsg();
            this.steer = 0;
            this.torque = 0;
        }

        public Car_comMsg(HeaderMsg header, byte steer, byte torque)
        {
            this.header = header;
            this.steer = steer;
            this.torque = torque;
        }

        public static Car_comMsg Deserialize(MessageDeserializer deserializer) => new Car_comMsg(deserializer);

        private Car_comMsg(MessageDeserializer deserializer)
        {
            this.header = HeaderMsg.Deserialize(deserializer);
            deserializer.Read(out this.steer);
            deserializer.Read(out this.torque);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.Write(this.steer);
            serializer.Write(this.torque);
        }

        public override string ToString()
        {
            return "Car_comMsg: " +
            "\nheader: " + header.ToString() +
            "\nsteer: " + steer.ToString() +
            "\ntorque: " + torque.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
