//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;
using RosMessageTypes.Std;

namespace RosMessageTypes.Crs
{
    [Serializable]
    public class Car_state_cartMsg : Message
    {
        public const string k_RosMessageName = "crs_msgs/car_state_cart";
        public override string RosMessageName => k_RosMessageName;

        public HeaderMsg header;
        public double x;
        public double y;
        public double z;
        public double roll;
        public double pitch;
        public double yaw;
        public double vx_w;
        public double vy_w;
        public double vz_w;
        public double v_tot;
        public double ax_w;
        public double ay_w;
        public double az_w;
        public double vx_b;
        public double vy_b;
        public double vz_b;
        public double ax_b;
        public double ay_b;
        public double az_b;
        public double droll;
        public double dpitch;
        public double dyaw;
        public double steer;
        public double[] additional_data;

        public Car_state_cartMsg()
        {
            this.header = new HeaderMsg();
            this.x = 0.0;
            this.y = 0.0;
            this.z = 0.0;
            this.roll = 0.0;
            this.pitch = 0.0;
            this.yaw = 0.0;
            this.vx_w = 0.0;
            this.vy_w = 0.0;
            this.vz_w = 0.0;
            this.v_tot = 0.0;
            this.ax_w = 0.0;
            this.ay_w = 0.0;
            this.az_w = 0.0;
            this.vx_b = 0.0;
            this.vy_b = 0.0;
            this.vz_b = 0.0;
            this.ax_b = 0.0;
            this.ay_b = 0.0;
            this.az_b = 0.0;
            this.droll = 0.0;
            this.dpitch = 0.0;
            this.dyaw = 0.0;
            this.steer = 0.0;
            this.additional_data = new double[0];
        }

        public Car_state_cartMsg(HeaderMsg header, double x, double y, double z, double roll, double pitch, double yaw, double vx_w, double vy_w, double vz_w, double v_tot, double ax_w, double ay_w, double az_w, double vx_b, double vy_b, double vz_b, double ax_b, double ay_b, double az_b, double droll, double dpitch, double dyaw, double steer, double[] additional_data)
        {
            this.header = header;
            this.x = x;
            this.y = y;
            this.z = z;
            this.roll = roll;
            this.pitch = pitch;
            this.yaw = yaw;
            this.vx_w = vx_w;
            this.vy_w = vy_w;
            this.vz_w = vz_w;
            this.v_tot = v_tot;
            this.ax_w = ax_w;
            this.ay_w = ay_w;
            this.az_w = az_w;
            this.vx_b = vx_b;
            this.vy_b = vy_b;
            this.vz_b = vz_b;
            this.ax_b = ax_b;
            this.ay_b = ay_b;
            this.az_b = az_b;
            this.droll = droll;
            this.dpitch = dpitch;
            this.dyaw = dyaw;
            this.steer = steer;
            this.additional_data = additional_data;
        }

        public static Car_state_cartMsg Deserialize(MessageDeserializer deserializer) => new Car_state_cartMsg(deserializer);

        private Car_state_cartMsg(MessageDeserializer deserializer)
        {
            this.header = HeaderMsg.Deserialize(deserializer);
            deserializer.Read(out this.x);
            deserializer.Read(out this.y);
            deserializer.Read(out this.z);
            deserializer.Read(out this.roll);
            deserializer.Read(out this.pitch);
            deserializer.Read(out this.yaw);
            deserializer.Read(out this.vx_w);
            deserializer.Read(out this.vy_w);
            deserializer.Read(out this.vz_w);
            deserializer.Read(out this.v_tot);
            deserializer.Read(out this.ax_w);
            deserializer.Read(out this.ay_w);
            deserializer.Read(out this.az_w);
            deserializer.Read(out this.vx_b);
            deserializer.Read(out this.vy_b);
            deserializer.Read(out this.vz_b);
            deserializer.Read(out this.ax_b);
            deserializer.Read(out this.ay_b);
            deserializer.Read(out this.az_b);
            deserializer.Read(out this.droll);
            deserializer.Read(out this.dpitch);
            deserializer.Read(out this.dyaw);
            deserializer.Read(out this.steer);
            deserializer.Read(out this.additional_data, sizeof(double), deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.Write(this.x);
            serializer.Write(this.y);
            serializer.Write(this.z);
            serializer.Write(this.roll);
            serializer.Write(this.pitch);
            serializer.Write(this.yaw);
            serializer.Write(this.vx_w);
            serializer.Write(this.vy_w);
            serializer.Write(this.vz_w);
            serializer.Write(this.v_tot);
            serializer.Write(this.ax_w);
            serializer.Write(this.ay_w);
            serializer.Write(this.az_w);
            serializer.Write(this.vx_b);
            serializer.Write(this.vy_b);
            serializer.Write(this.vz_b);
            serializer.Write(this.ax_b);
            serializer.Write(this.ay_b);
            serializer.Write(this.az_b);
            serializer.Write(this.droll);
            serializer.Write(this.dpitch);
            serializer.Write(this.dyaw);
            serializer.Write(this.steer);
            serializer.WriteLength(this.additional_data);
            serializer.Write(this.additional_data);
        }

        public override string ToString()
        {
            return "Car_state_cartMsg: " +
            "\nheader: " + header.ToString() +
            "\nx: " + x.ToString() +
            "\ny: " + y.ToString() +
            "\nz: " + z.ToString() +
            "\nroll: " + roll.ToString() +
            "\npitch: " + pitch.ToString() +
            "\nyaw: " + yaw.ToString() +
            "\nvx_w: " + vx_w.ToString() +
            "\nvy_w: " + vy_w.ToString() +
            "\nvz_w: " + vz_w.ToString() +
            "\nv_tot: " + v_tot.ToString() +
            "\nax_w: " + ax_w.ToString() +
            "\nay_w: " + ay_w.ToString() +
            "\naz_w: " + az_w.ToString() +
            "\nvx_b: " + vx_b.ToString() +
            "\nvy_b: " + vy_b.ToString() +
            "\nvz_b: " + vz_b.ToString() +
            "\nax_b: " + ax_b.ToString() +
            "\nay_b: " + ay_b.ToString() +
            "\naz_b: " + az_b.ToString() +
            "\ndroll: " + droll.ToString() +
            "\ndpitch: " + dpitch.ToString() +
            "\ndyaw: " + dyaw.ToString() +
            "\nsteer: " + steer.ToString() +
            "\nadditional_data: " + System.String.Join(", ", additional_data.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
