//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;
using RosMessageTypes.Std;
using RosMessageTypes.BuiltinInterfaces;

namespace RosMessageTypes.Crs
{
    [Serializable]
    public class Car_clockMsg : Message
    {
        public const string k_RosMessageName = "crs_msgs/car_clock";
        public override string RosMessageName => k_RosMessageName;

        //  Message that encapsulates an embedded system's clock.
        //  Its header is stamped by the host computer upon receival.
        public HeaderMsg header;
        public TimeMsg clock;
        //  in microseconds since arbitrary epoch

        public Car_clockMsg()
        {
            this.header = new HeaderMsg();
            this.clock = new TimeMsg();
        }

        public Car_clockMsg(HeaderMsg header, TimeMsg clock)
        {
            this.header = header;
            this.clock = clock;
        }

        public static Car_clockMsg Deserialize(MessageDeserializer deserializer) => new Car_clockMsg(deserializer);

        private Car_clockMsg(MessageDeserializer deserializer)
        {
            this.header = HeaderMsg.Deserialize(deserializer);
            this.clock = TimeMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.Write(this.clock);
        }

        public override string ToString()
        {
            return "Car_clockMsg: " +
            "\nheader: " + header.ToString() +
            "\nclock: " + clock.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
