//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;
using RosMessageTypes.Std;

namespace RosMessageTypes.Crs
{
    [Serializable]
    public class Car_wheel_speedMsg : Message
    {
        public const string k_RosMessageName = "crs_msgs/car_wheel_speed";
        public override string RosMessageName => k_RosMessageName;

        //  Wheel speed of all four wheels of a car, in rad/s
        public HeaderMsg header;
        public double front_left;
        public double front_right;
        public double rear_left;
        public double rear_right;

        public Car_wheel_speedMsg()
        {
            this.header = new HeaderMsg();
            this.front_left = 0.0;
            this.front_right = 0.0;
            this.rear_left = 0.0;
            this.rear_right = 0.0;
        }

        public Car_wheel_speedMsg(HeaderMsg header, double front_left, double front_right, double rear_left, double rear_right)
        {
            this.header = header;
            this.front_left = front_left;
            this.front_right = front_right;
            this.rear_left = rear_left;
            this.rear_right = rear_right;
        }

        public static Car_wheel_speedMsg Deserialize(MessageDeserializer deserializer) => new Car_wheel_speedMsg(deserializer);

        private Car_wheel_speedMsg(MessageDeserializer deserializer)
        {
            this.header = HeaderMsg.Deserialize(deserializer);
            deserializer.Read(out this.front_left);
            deserializer.Read(out this.front_right);
            deserializer.Read(out this.rear_left);
            deserializer.Read(out this.rear_right);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.Write(this.front_left);
            serializer.Write(this.front_right);
            serializer.Write(this.rear_left);
            serializer.Write(this.rear_right);
        }

        public override string ToString()
        {
            return "Car_wheel_speedMsg: " +
            "\nheader: " + header.ToString() +
            "\nfront_left: " + front_left.ToString() +
            "\nfront_right: " + front_right.ToString() +
            "\nrear_left: " + rear_left.ToString() +
            "\nrear_right: " + rear_right.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
