//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;
using RosMessageTypes.Std;

namespace RosMessageTypes.Crs
{
    [Serializable]
    public class Lighthouse_frameMsg : Message
    {
        public const string k_RosMessageName = "crs_msgs/lighthouse_frame";
        public override string RosMessageName => k_RosMessageName;

        public HeaderMsg header;
        public byte sensor_id;
        public byte polynomial;
        public ushort pulse_width;
        public uint sync_offset;
        public uint beam_word;
        public uint timestamp;

        public Lighthouse_frameMsg()
        {
            this.header = new HeaderMsg();
            this.sensor_id = 0;
            this.polynomial = 0;
            this.pulse_width = 0;
            this.sync_offset = 0;
            this.beam_word = 0;
            this.timestamp = 0;
        }

        public Lighthouse_frameMsg(HeaderMsg header, byte sensor_id, byte polynomial, ushort pulse_width, uint sync_offset, uint beam_word, uint timestamp)
        {
            this.header = header;
            this.sensor_id = sensor_id;
            this.polynomial = polynomial;
            this.pulse_width = pulse_width;
            this.sync_offset = sync_offset;
            this.beam_word = beam_word;
            this.timestamp = timestamp;
        }

        public static Lighthouse_frameMsg Deserialize(MessageDeserializer deserializer) => new Lighthouse_frameMsg(deserializer);

        private Lighthouse_frameMsg(MessageDeserializer deserializer)
        {
            this.header = HeaderMsg.Deserialize(deserializer);
            deserializer.Read(out this.sensor_id);
            deserializer.Read(out this.polynomial);
            deserializer.Read(out this.pulse_width);
            deserializer.Read(out this.sync_offset);
            deserializer.Read(out this.beam_word);
            deserializer.Read(out this.timestamp);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.Write(this.sensor_id);
            serializer.Write(this.polynomial);
            serializer.Write(this.pulse_width);
            serializer.Write(this.sync_offset);
            serializer.Write(this.beam_word);
            serializer.Write(this.timestamp);
        }

        public override string ToString()
        {
            return "Lighthouse_frameMsg: " +
            "\nheader: " + header.ToString() +
            "\nsensor_id: " + sensor_id.ToString() +
            "\npolynomial: " + polynomial.ToString() +
            "\npulse_width: " + pulse_width.ToString() +
            "\nsync_offset: " + sync_offset.ToString() +
            "\nbeam_word: " + beam_word.ToString() +
            "\ntimestamp: " + timestamp.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
