//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;
using RosMessageTypes.Std;

namespace RosMessageTypes.Crs
{
    [Serializable]
    public class Lighthouse_sweepMsg : Message
    {
        public const string k_RosMessageName = "crs_msgs/lighthouse_sweep";
        public override string RosMessageName => k_RosMessageName;

        public HeaderMsg header;
        public double angle_0;
        public double angle_1;
        public double angle_2;
        public double angle_3;
        //  Polynomial used in the sweep. The base station ID is polynomial >> 1.
        public byte polynomial;
        public uint first_timestamp;
        public uint sync_timestamp;
        public bool first_sweep;

        public Lighthouse_sweepMsg()
        {
            this.header = new HeaderMsg();
            this.angle_0 = 0.0;
            this.angle_1 = 0.0;
            this.angle_2 = 0.0;
            this.angle_3 = 0.0;
            this.polynomial = 0;
            this.first_timestamp = 0;
            this.sync_timestamp = 0;
            this.first_sweep = false;
        }

        public Lighthouse_sweepMsg(HeaderMsg header, double angle_0, double angle_1, double angle_2, double angle_3, byte polynomial, uint first_timestamp, uint sync_timestamp, bool first_sweep)
        {
            this.header = header;
            this.angle_0 = angle_0;
            this.angle_1 = angle_1;
            this.angle_2 = angle_2;
            this.angle_3 = angle_3;
            this.polynomial = polynomial;
            this.first_timestamp = first_timestamp;
            this.sync_timestamp = sync_timestamp;
            this.first_sweep = first_sweep;
        }

        public static Lighthouse_sweepMsg Deserialize(MessageDeserializer deserializer) => new Lighthouse_sweepMsg(deserializer);

        private Lighthouse_sweepMsg(MessageDeserializer deserializer)
        {
            this.header = HeaderMsg.Deserialize(deserializer);
            deserializer.Read(out this.angle_0);
            deserializer.Read(out this.angle_1);
            deserializer.Read(out this.angle_2);
            deserializer.Read(out this.angle_3);
            deserializer.Read(out this.polynomial);
            deserializer.Read(out this.first_timestamp);
            deserializer.Read(out this.sync_timestamp);
            deserializer.Read(out this.first_sweep);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.Write(this.angle_0);
            serializer.Write(this.angle_1);
            serializer.Write(this.angle_2);
            serializer.Write(this.angle_3);
            serializer.Write(this.polynomial);
            serializer.Write(this.first_timestamp);
            serializer.Write(this.sync_timestamp);
            serializer.Write(this.first_sweep);
        }

        public override string ToString()
        {
            return "Lighthouse_sweepMsg: " +
            "\nheader: " + header.ToString() +
            "\nangle_0: " + angle_0.ToString() +
            "\nangle_1: " + angle_1.ToString() +
            "\nangle_2: " + angle_2.ToString() +
            "\nangle_3: " + angle_3.ToString() +
            "\npolynomial: " + polynomial.ToString() +
            "\nfirst_timestamp: " + first_timestamp.ToString() +
            "\nsync_timestamp: " + sync_timestamp.ToString() +
            "\nfirst_sweep: " + first_sweep.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
