//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;
using RosMessageTypes.Std;

namespace RosMessageTypes.Crs
{
    [Serializable]
    public class Penalty_and_lap_countMsg : Message
    {
        public const string k_RosMessageName = "crs_msgs/penalty_and_lap_count";
        public override string RosMessageName => k_RosMessageName;

        public HeaderMsg header;
        public int cones_down;
        public int laps;
        public double penalty;

        public Penalty_and_lap_countMsg()
        {
            this.header = new HeaderMsg();
            this.cones_down = 0;
            this.laps = 0;
            this.penalty = 0.0;
        }

        public Penalty_and_lap_countMsg(HeaderMsg header, int cones_down, int laps, double penalty)
        {
            this.header = header;
            this.cones_down = cones_down;
            this.laps = laps;
            this.penalty = penalty;
        }

        public static Penalty_and_lap_countMsg Deserialize(MessageDeserializer deserializer) => new Penalty_and_lap_countMsg(deserializer);

        private Penalty_and_lap_countMsg(MessageDeserializer deserializer)
        {
            this.header = HeaderMsg.Deserialize(deserializer);
            deserializer.Read(out this.cones_down);
            deserializer.Read(out this.laps);
            deserializer.Read(out this.penalty);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.Write(this.cones_down);
            serializer.Write(this.laps);
            serializer.Write(this.penalty);
        }

        public override string ToString()
        {
            return "Penalty_and_lap_countMsg: " +
            "\nheader: " + header.ToString() +
            "\ncones_down: " + cones_down.ToString() +
            "\nlaps: " + laps.ToString() +
            "\npenalty: " + penalty.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
