//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Haptic
{
    [Serializable]
    public class TaxelMsg : Message
    {
        public const string k_RosMessageName = "haptic_msgs/Taxel";
        public override string RosMessageName => k_RosMessageName;

        public double intensity;

        public TaxelMsg()
        {
            this.intensity = 0.0;
        }

        public TaxelMsg(double intensity)
        {
            this.intensity = intensity;
        }

        public static TaxelMsg Deserialize(MessageDeserializer deserializer) => new TaxelMsg(deserializer);

        private TaxelMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.intensity);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.intensity);
        }

        public override string ToString()
        {
            return "TaxelMsg: " +
            "\nintensity: " + intensity.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
