#!/bin/bash

RED='\033[0;31m'
YELLOW='\033[0;33m'
WHITE='\033[0m'

update_index()
{
  ## $1: mode
  ## $2: new hash
  ## $3: filename
  git update-index --cacheinfo "$1,$2,$3"
}

update_working_tree()
{
  ## $1: old hash
  ## $2: new hash
  ## $3: filename
  git diff $1 $2 | sed "s|$1|$3|" | sed "s|$2|$3|" | git apply -
  if [ $? != 0 ]; then
    echo -e "${YELLOW}$3 in working tree cannot be formatted by applying the formatted changes in the staged copy.${WHITE}"
  fi
}

reformatted=0
failed=0

for filename in $(git diff --cached --name-only); do
  read -r mode old_hash others <<<"$(git ls-files --stage | grep "$filename")"

  # For C++ files. Note it's recommended to use the cmake-clang-tools from ANYbotics in each package's CMakeLists.txt
  if [[ "$filename" = @(*.h|*.hpp|*.cpp) ]]; then
    git cat-file -p $old_hash | clang-format -style=file --dry-run --Werror 2>/dev/null

    if [ $? = 1 ]; then
      echo "Auto-formatting C++ file: $filename"
      new_hash=$(git cat-file -p $old_hash | clang-format -style=file | git hash-object -w --stdin)

      update_index $mode $new_hash $filename
      update_working_tree $old_hash $new_hash $filename

      ((reformatted++))
    fi
  fi

  # For Python files
  if [[ "$filename" == *.py ]]; then
    git cat-file -p $old_hash | black -q --check -l 120 -
    black_return=$?

    if [ $black_return = 123 ]; then  # If black cannot format the python file, it returns 123
      echo "Failed to auto-format $filename"
      ((failed++))

    elif [ $black_return = 1 ]; then  # If black finds formatting is necessary for the python file, it returns 1
      echo "Auto-formatting Python file: $filename"
      new_hash=$(git cat-file -p $old_hash | black -q -l 120 - | git hash-object -w --stdin)

      update_index $mode $new_hash $filename
      update_working_tree $old_hash $new_hash $filename

      ((reformatted++))
    fi
  fi

done

if [ $failed -gt 0 -o $reformatted -gt 0 ]; then
  echo -e "${RED}Pre-commit check is not passed. Commit is aborted.${WHITE}"
  if [ $failed -gt 0 ]; then
    echo -e "${RED}$failed files cannont be formatted! Please fix the codes before creating commit.${WHITE}"
  fi
  if [ $reformatted -gt 0 ]; then
    echo -e "${YELLOW}$reformatted files have been reformatted! Please review the changes and commit again.${WHITE}"
  fi
  exit 1
else
  echo "No files are reformatted. Pre-commit check passed."
fi
